# docker-compose.yml

services:
  minio: # TODO: Migrate to garage, minio went crazy...
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: 'server /data --console-address ":9001"'
    restart: always
    volumes: 
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    depends_on:
      - minio
    command: mlflow server --backend-store-uri /data --default-artifact-root s3://${MLFLOW_BUCKET} --host 0.0.0.0 --serve-artifacts
    restart: always
    volumes: 
      - mlflow-data:/data
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_BUCKET=${MLFLOW_BUCKET}
      - MLFLOW_S3_IGNORE_TLS=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  labelstudio:
    image: heartexlabs/label-studio:latest
    depends_on:
      - minio
    restart: always
    volumes: 
      - ls-data:/data
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
  ner-api:
    build: ./NER_Api
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URL=${MLFLOW_TRACKING_URL}

volumes:
  minio-data:
  mlflow-data:
